import {PublicKey} from '@solana/web3.js';
export const HOUSE_PROGRAM_ID = new PublicKey("9pJ55KszBGk1Td3LbRrWLszAaiXg7YLW5oouLABJwsZg");
export const PREFIX = 'rng_house';
export const FEES = "fees";
export const TREASURY = 'treasury';
export const jare = "4tui4yfA6MNgLhjXmKBATrPvEUGseEeqQrqAyVHintUQ";
export const author = new PublicKey(jare);
export const house = new PublicKey("ASTu9TrWQkQL693SzAZ2533f871WUP3RxkW9y6nLGP9L");
export const DEFAULT_TIMEOUT = 30000;
export const DEVNET = "https://ssc-dao.genesysgo.net/";
export const MAINNET = "https://ssc-dao.genesysgo.net/";